### ISSUE TITLE
build  CherishOS

### ISSUE THREAD

**Issue by aohanhongzhi** [EvilAnsh/android_device_xiaomi_santoni#1]
![image](https://user-images.githubusercontent.com/37319319/166883138-48b74510-4565-4709-a571-e1d0ec08accb.png)
![image](https://user-images.githubusercontent.com/37319319/166883217-6ad804d2-244b-4bec-b118-e735e0e44ce6.png)
![image](https://user-images.githubusercontent.com/37319319/166883405-b9d1f20a-87d2-43a5-987e-37e196d3ec3e.png)
![image](https://user-images.githubusercontent.com/37319319/166883440-03fe8eb3-86b5-4fbc-a13f-d5edffee4708.png)
![image](https://user-images.githubusercontent.com/37319319/166883476-7d794275-7995-4705-b34c-aea2d5267192.png)
![image](https://user-images.githubusercontent.com/37319319/166883503-fbba20b1-b866-4dcb-b4df-9c1c4dd47bfe.png)

**Comment by EvilAnsh** [comment]
I didn't faced
